services:
  loki:
    image: grafana/loki:2.8.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - "./grafana/loki-config.yml:/etc/loki/loki-config.yml"
      - "./grafana/data:/loki"
    networks:
      - app-network

  promtail:
    image: grafana/promtail:2.8.0
    container_name: promtail
    volumes:
      - "./app1/storage/logs:/api/app1"
      - "./app2/storage/logs:/api/app2"
      - "./grafana/promtail-config.yml:/etc/promtail/config.yml"
      - "./grafana/file-targets.yml:/etc/promtail/file_targets.yml"
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - app-network

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:10.0.3
    ports:
      - "3000:3000"
    depends_on:
      - loki
    networks:
      - app-network